---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pipelines-as-code-secret
  namespace: openshift-pipelines
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-container
  target:
    creationPolicy: Owner
  data:
  - secretKey: github-private-key
    remoteRef:
      key: skull-cicd-github-private-key
      property: skull-cicd.2023-04-08.private-key.pem
  - secretKey: github-application-id
    remoteRef:
      key: skull-cicd
      property: github-application-id
  - secretKey: webhook.secret
    remoteRef:
      key: skull-cicd
      property: webhook.secret
