apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  defaultCertificate:
    name: cert-apps-hc1-openshift-pub
  nodePlacement:
    tolerations:
       - effect: NoSchedule
         key: node-role.kubernetes.io/master
