apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  replicas: 3
  defaultCertificate:
    name: cert-apps-hc1-openshift-pub
  nodePlacement:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/ingress: ""
    tolerations:
      - operator: Exists
