apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  labels:
    openshift.io/cluster-monitoring: "true"
  name: openshift-storage
spec: {}
