apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 50-masters-chrony-configuration
  resourceVersion: "1839"
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,CnBvb2wgMC5yaGVsLnBvb2wubnRwLm9yZyBpYnVyc3QKZHJpZnRmaWxlIC92YXIvbGliL2Nocm9ueS9kcmlmdAptYWtlc3RlcCAxLjAgMwpydGNzeW5jCmxvZ2RpciAvdmFyL2xvZy9jaHJvbnkKCnNlcnZlciAgbnRwMS5oZXR6bmVyLmRlICBpYnVyc3QKc2VydmVyICBudHAyLmhldHpuZXIuY29tIGlidXJzdApzZXJ2ZXIgIG50cDMuaGV0em5lci5uZXQgaWJ1cnN0Cgo=
        mode: 420
        overwrite: true
        path: /etc/chrony.conf
