apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: examples.openshift.pub cicd
    openshift.io/display-name: examples.openshift.pub cicd
    openshift.io/requester: robert@bohne.io
  labels:
  name: examples-openshift-pub
spec: {}
