apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-bohne-io
spec:
  acme:
    email: robert@bohne.io
    preferredChain: ""
    privateKeySecretRef:
      name: cloudflare-bohne-io-private-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            key: token
            name: cloudflare-api-token-bohne-io
          email: robert@bohne.io
        cnameStrategy: None
