---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hcloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-container
  target:
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      key: hc1-csi-hcloud-token
      property: token
