apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-immich-chart-upload
  namespace: photos
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: lvms-vg1
  volumeMode: Filesystem
