apiVersion: v1
kind: Node
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  labels:
    node-role.kubernetes.io/ingress: ""
  name: control-plane-0.hc1.openshift.pub
