apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  annotations:
    argocd.argoproj.io/sync-options: "ServerSideApply=true,Validate=false"
  name: openshift-gitops
spec:
  server:
    route:
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: reencrypt

