apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-of-apps
  namespace: openshift-gitops
spec:
  generators:
    - list:
        elements:
          - app: cert-manager
          - app: immich
          - app: chatbot-ui
          - app: skull-cicd
          - app: examples-openshift-pub-cicd
          - app: hetzner-ocp4-cicd
  template:
    metadata:
      name: 'app-{{ app }}'
      namespace: openshift-gitops
    spec:
      destination:
        server: https://kubernetes.default.svc
      project: default
      source:
        path: 'apps/onlogic/{{ app }}/'
        repoURL: https://github.com/rbo/gitops-cluster.git
        targetRevision: main
