apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-in-dotargocd
  namespace: openshift-gitops
spec:
  generators:
    - list:
        elements:
          - app: examples-openshift-pub-cicd
            repoURL: https://github.com/rbo/openshift-examples-web.git
            targetRevision: refactor-development
            namespace: examples-openshift-pub
  template:
    metadata:
      name: 'app-{{ app }}'
    spec:
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ namespace }}'
      project: default
      source:
        path: '.argocd/'
        repoURL: '{{ repoURL }}'
        targetRevision: '{{ targetRevision }}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true