---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-postgresql
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-container
  target:
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: immich-postgresql
      property: password
