apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - disable-self-provisioners.yaml
#  - enable-routingViaHost.yaml
#  - cluster-scope
#  - namespace
  # Install operators:
#  - ../../operators/openshift-pipelines/
  # Apps
#  - ../../apps/benito-greybeard-cicd/
