apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: photos.bohne.io
spec:
  commonName: photos.bohne.io
  dnsNames:
  - photos.bohne.io
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cloudflare-bohne-io
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: cert-photos-bohne-io
