apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-immich-chart
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "111"
spec:
  destination:
    namespace: photos
    server: "https://kubernetes.default.svc"
  source:
    path: charts/immich
    repoURL: "https://github.com/immich-app/immich-charts.git"
    targetRevision: immich-0.0.4
    helm:
      values: |-

        dnsConfig:
          options:
            - name: ndots
              value: "1"

        redis:
          enabled: true

        postgresql:
          enabled: false

        common_env:
          DB_HOSTNAME: "app-immich-postgresql-chart.photos.svc.cluster.local."
          DB_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: immich-postgresql
                key: password
          JWT_SECRET:
            valueFrom:
              secretKeyRef:
                name: immich-jwt
                key: password

        persistence:
          library:
            enabled: false
          upload:
            enabled: true
            mountPath: /usr/src/app/upload
            accessMode: ReadWriteOnce
            storageClass: lvms-vg1
            size: 100Gi

        server:
          image:
            repository: docker.io/altran1502/immich-server
            # renovate: datasource=docker depName=docker.io/altran1502/immich-server
            tag: v1.50.1

        microservice:
          image:
            repository: docker.io/altran1502/immich-server
            # renovate: datasource=docker depName=docker.io/altran1502/immich-server
            tag: v1.50.1

        machine_learning:
          image:
            repository: docker.io/altran1502/immich-machine-learning
            # renovate: datasource=docker depName=docker.io/altran1502/immich-machine-learning
            tag: v1.50.1
          command: null
          args: []
          env:
            NODE_ENV: "production"
            TRANSFORMERS_CACHE: /usr/src/app/.transformers_cache

        web:
          image:
            repository: docker.io/altran1502/immich-web
            # renovate: datasource=docker depName=docker.io/altran1502/immich-web
            tag: v1.50.1

        proxy:
          image:
            repository: docker.io/altran1502/immich-proxy
            # renovate: datasource=docker depName=docker.io/altran1502/immich-proxy
            tag: v1.50.1

        persistence:
          transformers-cache:
            enabled: true
            type: emptyDir
            mountPath: /usr/src/app/.transformers_cache

  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
