apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-immich-chart
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "111"
spec:
  destination:
    namespace: photos
    server: "https://kubernetes.default.svc"
  source:
    path: charts/immich
    repoURL: "https://github.com/rbo/immich-charts.git"
    targetRevision: onlogic
    helm:
      values: |-

        dnsConfig:
          options:
            - name: ndots
              value: "1"

        ingress:
          main:
            enabled: true
            annotations:
              # proxy-body-size is set to 0 to remove the body limit on file uploads
              # nginx.ingress.kubernetes.io/proxy-body-size: "0"
            hosts:
              - host: photos.bohne.io
                paths:
                  - path: "/"
            tls:
              - hosts:
                  - photos.bohne.io
                secretName: cert-photos-bohne-io

        immich:
          persistence:
            # Main data store for all photos shared between different components.
            library:
              # Automatically creating the library volume is not supported by this chart
              # You have to specify an existing PVC to use
              existingClaim: app-immich-chart-upload

        redis:
          enabled: true

        postgresql:
          enabled: false

        typesense:
          enabled: true
          persistence:
            tsdata:
              enabled: true
              accessMode: ReadWriteOnce
              size: 8Gi
              storageClass: lvms-vg1

        env:
          DB_HOSTNAME: "app-immich-postgresql-chart.photos.svc.cluster.local."
          DB_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: immich-postgresql
                key: password
          JWT_SECRET:
            valueFrom:
              secretKeyRef:
                name: immich-jwt
                key: password

        machine_learning:
          persistence:
            cache:
              enabled: true
              size: 10Gi
              type: pvc
              accessMode: ReadWriteOnce
              storageClass: lvms-vg1

  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
