apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  replicas: 1
  defaultCertificate:
    name: cert-apps-pumuckl-openshift-pub
