apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apps-hc1-openshift-pub
spec:
  commonName: "*.apps.pumuckl.openshift.pub"
  dnsNames:
  - "*.apps.pumuckl.openshift.pub"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cloudflare-openshift-pub
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: cert-apps-pumuckl-openshift-pub
