---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pipelines-as-code-secret
  namespace: openshift-pipelines
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-container
  target:
    creationPolicy: Owner
  data:
  - secretKey: github-private-key
    remoteRef:
      key: benito-greybeard-cicd-private-key
      property: benito-greybeard-cicd.2023-09-20.private-key
  - secretKey: github-application-id
    remoteRef:
      key: benito-greybeard-cicd
      property: app-id
  - secretKey: webhook.secret
    remoteRef:
      key: benito-greybeard-cicd
      property: webhook-secret
