apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-openshift-pub
spec:
  acme:
    email: robert@bohne.io
    preferredChain: ""
    privateKeySecretRef:
      name: cloudflare-openshift-pub-private-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            key: token
            name: cloudflare-api-token-openshift-pub
          email: robert@bohne.io
        cnameStrategy: None
